sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk: # TODO: should work with java 1.7
  - oraclejdk8
install:
- ./mvnw install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script:
- './mvnw install -nsu -Dmaven.test.redirectTestOutputToFile=true'
